version: '3'
services:
  api:
    build: ./backend
    container_name: backend_c
    ports: 
      - '8080:8080'
    volumes:
      - ./backend:/app
      - ./app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
